dist: trusty
sudo: required

language: node_js

node_js:
  12

branches:
  only:
    - writing

install:
  - npm install -g hexo
  - npm install -g hexo-cli
  - npm install

script:
  - hexo clean
  - hexo generate

after_success:
  - hexo deploy > /dev/null

notifications: # 设置通知项
  email: true