dist: trusty

language: node_js

node_js:
  - 12
branches:
  only:
    - writing

install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  keep_history: true
  github_token: ${GIT_REPO_TOKEN}
  target_branch: master
  on:
    branch: writing
