dist: trusty

language: node_js

node_js:
  - 12

branches:
  only:
    - writing

install:
  - source update.sh

script:
  - hexo clean
  - hexo generate

after_success:
  - hexo deploy > /dev/null

notifications: # 设置通知项
  email: true