dist: trusty
sudo: required

language: node_js

node_js:
  - 12

branches:
  only:
    - writing

install:
  - npm install -g hexo-cli
  - npm install
  - sed -i'' "s~git@github.com:SyameimaruKibou/syameimarukibou.github.io.git~https://${GIT_REPO_TOKEN}@github.com/SyameimaruKibou/syameimarukibou.github.io.git~" _config.yml
  - cat _config.yml

script:
  - hexo clean
  - hexo generate

after_success:
  - hexo deploy > /dev/null

notifications: # 设置通知项
  email: true